name: Gradle build on pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v3

      - name: Setup Java Development Kit 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Gradle project
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build